services:
  mongo:
    image: mongo:7
    container_name: boolean-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: boolean-redis
    ports:
      - '6379:6379'

volumes:
  mongo_data:
